// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Filmoteka
//
//	---
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /Filmoteka/
//	Version: 0.0.1
//	Contact: <katucha00@mail.ru>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
